Repository neptune-ai/examples, pull requests merged in 2024-08, with the labels that each got.

#341 chore: Update notebook text to match the updated method for adding new tags to runs
  how-to-guides/organize-ml-experimentation/notebooks/Organize_ML_runs.ipynb
Labels: documentation

#340 feat: Add group tags to optuna example
  README.md
  integrations-and-supported-tools/optuna/notebooks/Neptune_Optuna_integration.ipynb
  integrations-and-supported-tools/optuna/scripts/Neptune_Optuna_integration_load_study.py
  integrations-and-supported-tools/optuna/scripts/Neptune_Optuna_integration_log_study_and_trial_level.py
  integrations-and-supported-tools/optuna/scripts/run_examples.sh
Labels: documentation, enhancement

#342 fix: remove error from notebook JSON rendering
  how-to-guides/neptune-hpo/notebooks/Neptune_hpo.ipynb
Labels: bug, documentation
